### PR TITLE
rebuilding website

### PR DESCRIPTION
**Pull request by shayanfpg9**
Hi 👋
i have been rebuilding this document with 🧐
more bootstrap,
less code smell,
more readable and
more beautiful

### CODE REVIEW

**Comment by shayanfpg9** [comment]
now just need to make dark mode with css vars and fainal checkup

**Comment by shayanfpg9** [comment]
now dark/light mode is created and
It also uses the light/dark mode of the system

**Comment by shayanfpg9** [comment]
Now I think it's over
If I find a problem, I will fix it soon

**Comment by Bahman-Ahmadi** [comment]
> Hi 👋 i have been rebuilding this document with 🧐 more bootstrap, less code smell, more readable and more beautiful

Hi Bro , I really surprised by your changes so thank you. I will merge your changes.

**Pull request merged**
